export const GOOGLE_CONFIG={CLIENT_ID:'COLOCA_AQUI_O_GOOGLE_CLIENT_ID',API_KEY:'COLOCA_AQUI_A_GOOGLE_API_KEY',SCOPES:'https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/spreadsheets'}
export function loadScript(src){return new Promise((res,rej)=>{if(document.querySelector(`script[src="${src}"]`)){res();return}const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.body.appendChild(s)})}
let tokenClient=null
export async function initGoogle(){await loadScript('https://apis.google.com/js/api.js');await loadScript('https://accounts.google.com/gsi/client');await new Promise(r=>window.gapi.load('client',async()=>{await window.gapi.client.init({apiKey:GOOGLE_CONFIG.API_KEY,discoveryDocs:['https://www.googleapis.com/discovery/v1/apis/drive/v3/rest','https://sheets.googleapis.com/$discovery/rest?version=v4']});r()}));tokenClient=window.google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CONFIG.CLIENT_ID,scope:GOOGLE_CONFIG.SCOPES,callback:''});return true}
export async function signInGoogle(){await initGoogle();return new Promise((res,rej)=>{tokenClient.callback=(r)=>r.error?rej(r):res(r);tokenClient.requestAccessToken({prompt:'consent'})})}
export async function createDriveFolder(name='2YOU Academy'){const r=await window.gapi.client.drive.files.create({resource:{name,mimeType:'application/vnd.google-apps.folder'},fields:'id,name'});return r.result}
export async function uploadPdfToDrive(fileName,blob,folderId=null){const metadata={name:fileName,mimeType:'application/pdf',...(folderId?{parents:[folderId]}:{})};const form=new FormData();form.append('metadata',new Blob([JSON.stringify(metadata)],{type:'application/json'}));form.append('file',blob);const token=window.gapi.client.getToken()?.access_token;const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',{method:'POST',headers:new Headers({Authorization:`Bearer ${token}`}),body:form});return await r.json()}
export async function createSpreadsheet(title='2YOU Academy Dados'){const r=await window.gapi.client.sheets.spreadsheets.create({properties:{title}});return r.result}
export async function appendSheetRow(spreadsheetId,sheetName,row){const r=await window.gapi.client.sheets.spreadsheets.values.append({spreadsheetId,range:`${sheetName}!A:Z`,valueInputOption:'USER_ENTERED',insertDataOption:'INSERT_ROWS',resource:{values:[row]}});return r.result}
