import React,{useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{Home,Users,ClipboardList,Star,Euro,PlaySquare,CalendarDays,Menu,Bell,UserCircle,Plus,Search,Clock,MapPin,ChevronRight,Trophy,BarChart3,Cloud,FileDown,UploadCloud}from'lucide-react'
import{signInGoogle,createDriveFolder,uploadPdfToDrive}from'./services/google.js'
import{exportElementToPdf}from'./services/pdf.js'
import'./styles.css'
const mods=['Futsal','Futebol','Voleibol'], levels=['Sub-7','Sub-9','Sub-11','Sub-13','Sub-15','Sub-17','Juniores','Seniores']
const athletes=[['Alexandre Sousa','Sub-13','Futsal','Ala','Em atraso',79],['Diogo Marques','Sub-13','Futebol','Médio','Pago',82],['Gonçalo Ferreira','Sub-15','Futsal','Fixo','Pago',86],['Miguel Santos','Sub-15','Voleibol','Zona 4','Em atraso',73],['Rodrigo Almeida','Seniores','Futsal','Pivot','Pago',88]].map(a=>({name:a[0],level:a[1],mod:a[2],pos:a[3],pay:a[4],score:a[5]}))
const evals={Técnica:['Passe','Receção','Remate','Drible','Controlo de bola'],Tática:['Posicionamento','Leitura de jogo','Decisão'],Física:['Velocidade','Resistência','Agilidade','Força'],Mental:['Liderança','Disciplina','Concentração','Espírito de equipa']}
const train={Futsal:['Treino Técnico','Treino Tático','Finalização','Guarda-redes'],Futebol:['Posicional','Finalização','Transições','Guarda-redes'],Voleibol:['Serviço','Receção','Ataque','Bloco','Defesa']}
function App(){const[tab,setTab]=useState('inicio'),[mod,setMod]=useState('Futsal'),[level,setLevel]=useState('Sub-13'),[g,setG]=useState('offline'),[folder,setFolder]=useState(null)
async function connect(){try{setG('a ligar...');await signInGoogle();const f=await createDriveFolder('Cavadas Academy');setFolder(f);setG('ligado')}catch(e){console.error(e);setG('erro');alert('Verifica CLIENT_ID e API_KEY em src/services/google.js')}}
async function pdf(name='Cavadas_Academy.pdf'){try{const b=await exportElementToPdf('pdf-area',name);if(g==='ligado'){await uploadPdfToDrive(name,b,folder?.id);alert('PDF gerado e enviado ao Drive')}else alert('PDF gerado. Liga ao Google para enviar ao Drive.')}catch(e){console.error(e);alert('Erro ao gerar PDF')}}
const props={mod,setMod,level,setLevel,g,connect,pdf}
const pages={inicio:<Inicio {...props}/>,atletas:<Atletas {...props}/>,treinos:<Treinos {...props}/>,avaliacao:<Avaliacao {...props}/>,biblioteca:<Biblioteca {...props}/>,pagamentos:<Pagamentos {...props}/>,mais:<Mais {...props}/>}
return <div className="phone"><Header g={g} connect={connect}/><main id="pdf-area">{pages[tab]}</main><nav>{[['inicio','Início',<Home/>],['atletas','Atletas',<Users/>],['treinos','Treinos',<ClipboardList/>],['avaliacao','Avaliação',<Star/>],['mais','Mais',<Menu/>]].map(x=><Tab key={x[0]} id={x[0]} tab={tab} setTab={setTab} icon={x[2]} label={x[1]}/>)}</nav></div>}
function Header({g,connect}){return <header><img src={`${import.meta.env.BASE_URL}logo-2you.png`} className="header-logo"/><div className="header-title"><h1>CAVADAS ACADEMY</h1><p>DA ACADEMIA À COMPETIÇÃO</p></div><button onClick={connect} className={g==='ligado'?'icon-button ok':'icon-button'}><Cloud size={18}/></button><Bell size={20}/><UserCircle size={23}/></header>}
function Inicio(p){return <section><div className="hello"><div><h2>Olá, Treinador! 👋</h2><p>Bem-vindo à Cavadas Academy</p></div><span>20 MAI</span></div><Filters {...p}/><GoogleCard {...p}/><Title text="Visão geral"/><div className="cards4"><Metric icon={<Users/>} value="24" label="Atletas"/><Metric icon={<ClipboardList/>} value="8" label="Treinos"/><Metric icon={<Star/>} value="3" label="Avaliações"/><Metric icon={<Euro/>} value="2" label="Em atraso"/></div><Title text="Próximo treino"/><Training title={train[p.mod][0]} mod={p.mod} level={p.level} green/><Action icon={<FileDown/>} label="Gerar PDF do painel" onClick={()=>p.pdf('Dashboard.pdf')}/><Title text="Alertas"/><Notice title="Avaliação física pendente" desc="5 atletas por avaliar"/><Notice title="Pagamento de Maio em atraso" desc="2 atletas em atraso"/></section>}
function Atletas(p){const list=useMemo(()=>athletes.filter(a=>a.mod===p.mod&&(p.level==='Todos'||a.level===p.level)),[p.mod,p.level]);return <section><Top title="Atletas"/><Filters {...p}/><SearchBox/>{list.map(a=><Row key={a.name} a={a}/>)}</section>}
function Treinos(p){return <section><Top title="Treinos"/><Filters {...p}/><div className="subtabs"><b>Plano semanal</b><span>Plano mensal</span><span>Plano anual</span><span>Presenças</span></div>{train[p.mod].map(t=><Training key={t} title={t} mod={p.mod} level={p.level}/>) }<Action icon={<FileDown/>} label="Gerar PDF do plano de treino" onClick={()=>p.pdf('Plano_Treino.pdf')}/></section>}
function Avaliacao(p){return <section><Top title="Avaliação"/><Filters {...p}/><div className="profile"><Avatar text="AS"/><div><b>Alexandre Sousa</b><p>{p.level} · {p.mod}</p></div></div><div className="radar"><div></div><span>Gráfico de evolução</span></div>{Object.entries(evals).map(([k,v])=><div className="eval-block" key={k}><h3>{k}</h3>{v.map((i,n)=><Eval key={i} label={i} value={(n%5)+1}/>)}</div>)}<div className="scale"><b>Escala</b><p>1 - Insuficiente · 2 - Suficiente · 3 - Bom · 4 - Muito Bom · 5 - Excelente</p></div><Action icon={<FileDown/>} label="Gerar PDF da avaliação" onClick={()=>p.pdf('Avaliacao.pdf')}/></section>}
function Biblioteca(p){return <section><Top title="Biblioteca"/><div className="chips">{mods.map(m=><button key={m} onClick={()=>p.setMod(m)} className={m===p.mod?'active':''}>{m}</button>)}</div><div className="google-card"><UploadCloud/><div><b>Pasta de vídeos</b><p>Drive preparado para vídeos, animações e PDFs.</p></div></div>{['Exercícios Futsal','Exercícios Futebol','Exercícios Voleibol','Animações Táticas','PDF dos Exercícios'].map(v=><Video key={v} text={v}/>)}</section>}
function Pagamentos(p){return <section><Top title="Pagamentos"/>{athletes.map(a=><div className="pay" key={a.name}><Avatar text={initials(a.name)}/><div><b>{a.name}</b><p>Mensalidade · Inscrição · Material</p></div><div><strong>€20,00</strong><em className={a.pay==='Pago'?'ok':'bad'}>{a.pay}</em></div></div>)}<Action icon={<FileDown/>} label="Relatório financeiro" onClick={()=>p.pdf('Financeiro.pdf')}/></section>}
function Mais(p){return <section><Top title="Mais"/><Btn icon={<Cloud/>} text={`Google: ${p.g}`} onClick={p.connect}/><Btn icon={<PlaySquare/>} text="Biblioteca de vídeos"/><Btn icon={<CalendarDays/>} text="Google Calendar"/><Btn icon={<FileDown/>} text="Relatórios PDF" onClick={()=>p.pdf('Relatorio.pdf')}/><Btn icon={<Trophy/>} text="Treina · Evolui · Supera · Vence"/></section>}
function Filters({mod,setMod,level,setLevel}){return <><div className="chips">{mods.map(m=><button key={m} onClick={()=>setMod(m)} className={m===mod?'active':''}>{m}</button>)}</div><div className="levels">{['Todos',...levels].map(l=><button key={l} onClick={()=>setLevel(l)} className={l===level?'active':''}>{l}</button>)}</div></>}
function Metric({icon,value,label}){return <div className="metric">{React.cloneElement(icon,{size:30})}<strong>{value}</strong><span>{label}</span></div>}
function Title({text}){return <h3 className="section-title">{text}</h3>}
function Notice({title,desc}){return <div className="notice"><Bell/><div><b>{title}</b><p>{desc}</p></div></div>}
function Top({title}){return <div className="top"><h2>{title}</h2><button><Plus size={18}/></button></div>}
function SearchBox(){return <div className="search"><Search size={16}/><input placeholder="Pesquisar atleta..."/></div>}
function Avatar({text}){return <div className="avatar">{text}</div>}
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('')}
function Training({title,mod,level,green=false}){return <div className={green?'train green':'train'}><div><b>{title}</b><p><Clock size={14}/> 19:00 - 20:30</p><p><MapPin size={14}/> Pavilhão Municipal · {mod}</p></div><span>{level}</span></div>}
function Row({a}){return <div className="row"><Avatar text={initials(a.name)}/><div><b>{a.name}</b><p>{a.mod} · {a.pos}</p></div><span>{a.level}</span><ChevronRight size={18}/></div>}
function Eval({label,value}){return <div className="eval-line"><span>{label}</span><div>{[1,2,3,4,5].map(n=><i key={n} className={n<=value?'on':''}></i>)}</div><b>{value}</b></div>}
function Video({text}){return <div className="video"><div className="thumb"><PlaySquare/></div><div><b>{text}</b><p>Vídeo · Animação · PDF</p></div><ChevronRight size={18}/></div>}
function GoogleCard({g,connect}){return <div className="google-card"><Cloud/><div><b>Google Drive + Sheets + Calendar</b><p>Estado: {g}</p></div><button onClick={connect}>Ligar</button></div>}
function Action({icon,label,onClick}){return <button className="pdf" onClick={onClick}>{icon}{label}</button>}
function Btn({icon,text,onClick}){return <button className="btn" onClick={onClick}>{icon}<b>{text}</b><ChevronRight/></button>}
function Tab({id,tab,setTab,icon,label}){return <button className={tab===id?'active':''} onClick={()=>setTab(id)}>{React.cloneElement(icon,{size:20})}<span>{label}</span></button>}
createRoot(document.getElementById('root')).render(<App/>)
