import React,{useState}from'react'
import{createRoot}from'react-dom/client'
import{Home,Users,ClipboardList,Star,Euro,PlaySquare,CalendarDays,Menu,Bell,UserCircle,Plus,Search,Clock,MapPin,ChevronRight,Trophy,BarChart3,Cloud,FileDown,UploadCloud}from'lucide-react'
import{initGoogle,signInGoogle,createDriveFolder,uploadPdfToDrive}from'./services/google.js'
import{exportElementToPdf}from'./services/pdf.js'
import'./styles.css'
const athletes=[{nome:'Alexandre Sousa',esc:'Sub-13',mod:'Futsal',pos:'Ala',pag:'Em atraso'},{nome:'Diogo Marques',esc:'Sub-13',mod:'Futebol',pos:'Médio',pag:'Pago'},{nome:'Gonçalo Ferreira',esc:'Sub-15',mod:'Futsal',pos:'Fixo',pag:'Pago'},{nome:'Miguel Santos',esc:'Sub-15',mod:'Voleibol',pos:'Zona 4',pag:'Em atraso'},{nome:'Rodrigo Almeida',esc:'Sub-17',mod:'Futsal',pos:'Pivot',pag:'Pago'}]
const videos=[['Passe e desmarcação','Futsal','Técnica'],['Finalização após apoio','Futsal','Finalização'],['Receção orientada','Futebol','Técnica'],['Manchete e deslocamento','Voleibol','Técnica']]
function App(){const[tab,setTab]=useState('inicio');const[googleStatus,setGoogleStatus]=useState('offline');const[folder,setFolder]=useState(null);async function connectGoogle(){try{setGoogleStatus('a ligar...');await initGoogle();await signInGoogle();const f=await createDriveFolder('2YOU Academy');setFolder(f);setGoogleStatus('ligado')}catch(e){console.error(e);setGoogleStatus('erro');alert('Confirma CLIENT_ID e API_KEY em src/services/google.js')}}async function makePdf(){try{const blob=await exportElementToPdf('pdf-area','2YOU_Academy.pdf');if(googleStatus==='ligado'){await uploadPdfToDrive('2YOU_Academy.pdf',blob,folder?.id);alert('PDF gerado e guardado no Drive')}else alert('PDF gerado. Liga ao Google para enviar ao Drive.')}catch(e){console.error(e);alert('Erro ao gerar PDF')}}const shared={googleStatus,connectGoogle,makePdf};const pages={inicio:<Inicio {...shared}/>,atletas:<Atletas/>,treinos:<Treinos makePdf={makePdf}/>,avaliacao:<Avaliacao makePdf={makePdf}/>,pagamentos:<Pagamentos/>,videos:<Videos makePdf={makePdf}/>,calendario:<Calendario/>,mais:<Mais {...shared}/>};return <div className='phone'><Header {...shared}/><main id='pdf-area'>{pages[tab]}</main><nav><Tab id='inicio'tab={tab}setTab={setTab}icon={<Home/>}label='Início'/><Tab id='atletas'tab={tab}setTab={setTab}icon={<Users/>}label='Atletas'/><Tab id='treinos'tab={tab}setTab={setTab}icon={<ClipboardList/>}label='Treinos'/><Tab id='avaliacao'tab={tab}setTab={setTab}icon={<Star/>}label='Avaliação'/><Tab id='mais'tab={tab}setTab={setTab}icon={<Menu/>}label='Mais'/></nav></div>}
function Header({googleStatus,connectGoogle}){return <header><img src='/logo-2you.png'/><div><h1>2YOU ACADEMY</h1><p>TREINA · EVOLUI · SUPERA · VENCE</p></div><button onClick={connectGoogle}className={googleStatus==='ligado'?'g ok':'g'}><Cloud size={18}/></button><Bell size={20}/><UserCircle size={23}/></header>}
function Inicio({googleStatus,connectGoogle,makePdf}){return <section><div className='hello'><div><h2>Olá, Treinador! 👋</h2><p>Bem-vindo à 2YOU Academy</p></div><span>20 MAI</span></div><div className='google-card'><Cloud/><div><b>Google Drive + Sheets</b><p>Estado: {googleStatus}</p></div><button onClick={connectGoogle}>Ligar</button></div><h3>Visão geral</h3><div className='cards4'><Metric icon={<Users/>}v='24't='Atletas'/><Metric icon={<ClipboardList/>}v='8't='Treinos'/><Metric icon={<Star/>}v='3't='Avaliações'/><Metric icon={<Euro/>}v='2't='Em atraso'/></div><h3>Próximo treino</h3><Training title='Treino Técnico'esc='SUB-13'time='19:00 - 20:30'green/><button className='pdf' onClick={makePdf}><FileDown/> Gerar PDF do painel</button><Notice title='Avaliação física pendente'desc='5 atletas por avaliar'/><Notice title='Pagamento de Maio em atraso'desc='2 atletas em atraso'/></section>}
function Atletas(){return <section><Top title='Atletas'/><SearchBox/>{athletes.map(a=><Row key={a.nome} a={a}/>)}</section>}
function Treinos({makePdf}){return <section><Top title='Treinos'/><Tabs/><Week/><Training title='Treino Técnico'esc='SUB-13'time='19:00 - 20:30'/><Training title='Treino Tático'esc='SUB-15'time='19:00 - 21:30'/><button className='pdf'onClick={makePdf}><FileDown/> Gerar PDF do plano</button></section>}
function Avaliacao({makePdf}){return <section><Top title='Avaliação'/><Tabs names={['TÉCNICA','TÁTICA','FÍSICA','COMP.']}/><div className='profile'><Avatar text='AS'/><div><b>Alexandre Sousa</b><p>Sub-13 · Futsal</p></div></div><div className='radar'><div></div><span>Técnica</span></div><div className='progress'><p>Evolução geral <b>79%</b></p><i><em style={{width:'79%'}}></em></i></div><button className='pdf'onClick={makePdf}><FileDown/> Gerar PDF da avaliação</button></section>}
function Pagamentos(){return <section><Top title='Pagamentos'/>{athletes.map(a=><div className='pay'key={a.nome}><Avatar text={initials(a.nome)}/><div><b>{a.nome}</b><p>Mensalidade Maio</p></div><div><strong>€20,00</strong><em className={a.pag==='Pago'?'ok':'bad'}>{a.pag}</em></div></div>)}</section>}
function Videos({makePdf}){return <section><Top title='Vídeos / Animações'/><SearchBox placeholder='Pesquisar vídeos...'/><div className='google-card'><UploadCloud/><div><b>Pasta de vídeos</b><p>Preparado para Google Drive.</p></div></div>{videos.map(v=><div className='video'key={v[0]}><div className='thumb'><PlaySquare/></div><div><b>{v[0]}</b><p>{v[1]} · {v[2]}</p></div></div>)}<button className='pdf'onClick={makePdf}><FileDown/> Gerar PDF dos exercícios</button></section>}
function Calendario(){return <section><Top title='Calendário'/><div className='calendar'>MAIO / 2024<br/><br/>20 21 22 23 24 25 26</div><Training title='Treino Técnico'esc='SUB-13'time='19:00 - 20:30'/></section>}
function Mais({googleStatus,connectGoogle,makePdf}){return <section><Top title='Mais'/><Btn icon={<Cloud/>}text={'Google: '+googleStatus}onClick={connectGoogle}/><Btn icon={<FileDown/>}text='Gerar PDF'onClick={makePdf}/><Btn icon={<Euro/>}text='Pagamentos'/><Btn icon={<PlaySquare/>}text='Vídeos / Animações'/><Btn icon={<Users/>}text='Portal dos Pais'/><Btn icon={<BarChart3/>}text='Relatórios'/><Btn icon={<Trophy/>}text='Treina · Evolui · Supera · Vence'/></section>}
function Metric({icon,v,t}){return <div className='metric'>{React.cloneElement(icon,{size:30})}<strong>{v}</strong><span>{t}</span></div>}
function Notice({title,desc}){return <div className='notice'><Bell/><div><b>{title}</b><p>{desc}</p></div></div>}
function Top({title}){return <div className='top'><h2>{title}</h2><button><Plus size={18}/></button></div>}
function SearchBox({placeholder='Pesquisar atleta...'}){return <div className='search'><Search size={16}/><input placeholder={placeholder}/></div>}
function Training({title,esc,time,green}){return <div className={green?'train green':'train'}><div><b>{title}</b><p><Clock size={14}/> {time}</p><p><MapPin size={14}/> Pavilhão Municipal</p></div><span>{esc}</span></div>}
function Tabs({names=['SEMANA','MÊS','LISTA']}){return <div className='tabs'><b>{names[0]}</b>{names.slice(1).map(n=><span key={n}>{n}</span>)}</div>}
function Week(){return <div className='week'>{['SEG 20','TER 21','QUA 22','QUI 23','SEX 24','SÁB 25','DOM 26'].map((d,i)=><b className={i===1?'active':''}key={d}>{d}</b>)}</div>}
function Row({a}){return <div className='row'><Avatar text={initials(a.nome)}/><div><b>{a.nome}</b><p>{a.mod} · {a.pos}</p></div><span>{a.esc}</span><ChevronRight size={18}/></div>}
function Avatar({text}){return <div className='avatar'>{text}</div>}
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('')}
function Btn({icon,text,onClick}){return <button className='btn'onClick={onClick}>{icon}<b>{text}</b><ChevronRight/></button>}
function Tab({id,tab,setTab,icon,label}){return <button className={tab===id?'active':''}onClick={()=>setTab(id)}>{React.cloneElement(icon,{size:20})}<span>{label}</span></button>}
createRoot(document.getElementById('root')).render(<App/>)
